# Generated by Django 5.1.3 on 2024-12-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingstation',
            name='over_votes',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='pollingstation',
            name='rejected_ballots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pollingstation',
            name='total_votes_cast',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='vote',
            name='votes',
            field=models.PositiveIntegerField(),
        ),
    ]
